# Generated by Django 5.1.1 on 2024-10-13 17:39

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media/images/', validators=[petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
