# Generated by Django 5.1.3 on 2024-11-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
